<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="${target_namespace}"
        xmlns:tns="${target_namespace}"
        elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema" >
<!-- 
     This XMLSchema was auto-generated by ${generating_program}<#if generated_date??>, ${generated_date?datetime}</#if>.
--> 

<#list ospecs as ospec>
  <#assign el_name = ospec.rowElementName><#t>
  <#assign el_type_name = typeNamer.getRowElementTypeName(ospec.relationId)/><#t>
  <#assign list_el_name = ospec.rowCollectionElementName/><#t>
  <#assign list_el_type_name = typeNamer.getRowCollectionElementTypeName(ospec.relationId)/><#t>
  
  <#if !(toplevel_el_rels??) || toplevel_el_rels?seq_contains(ospec.relationId)>
  <element name="${el_name}" type="tns:${el_type_name}"/>
  </#if>

  <complexType name="${el_type_name}">
    <sequence>
      <!-- fields -->
      <#list ospec.includedFields as f>
      <#assign field_xs_type = qgen.getXmlSchemaTypeForJdbcTypeCode(f.jdbcTypeCode)>
      <element name="${f.name?lower_case}" type="${field_xs_type}" minOccurs="<#if f.nullable>0<#else>1</#if>"<#if f.nullable> nillable="true"</#if>/>
      </#list>
      
      <!-- child elements -->
      <#list ospec.childOutputSpecs as c_ospec>
        <#if inline_el_collections><#t>
      <element name="${c_ospec.rowElementName}" type="tns:${typeNamer.getRowElementTypeName(c_ospec.relationId)}" minOccurs="0" maxOccurs="unbounded"/>
        <#else><#t>
      <element name="${c_ospec.rowCollectionElementName}" type="tns:${typeNamer.getRowCollectionElementTypeName(c_ospec.relationId)}" minOccurs="${child_els_opt?string('0','1')}"/>
        </#if><#t>
      </#list>
      
      <!-- parent elements -->
      <#list ospec.parentOutputSpecs as p_ospec>
      <element name="${p_ospec.rowElementName}" type="tns:${typeNamer.getRowElementTypeName(p_ospec.relationId)}" minOccurs="${parent_els_opt?string('0','1')}"/>
      </#list>
    </sequence>
  </complexType>

  <#if !toplevel_list_el_rels?? || toplevel_list_el_rels?seq_contains(ospec.relationId)>
  <element name="${list_el_name}" type="tns:${list_el_type_name}"/>
  </#if>

  <complexType name="${list_el_type_name}">
    <sequence>
      <element name="${el_name}" type="tns:${el_type_name}"	minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>
  
</#list>
</schema>