<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="${target_namespace}"
        xmlns:tns="${target_namespace}"
        elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema" >
<!-- 
     This XMLSchema was auto-generated by ${generating_program}, ${generated_date?datetime}.
--> 

<#list ospecs as ospec>
  <#assign relmd = qgen.databaseMetaData.getRelationMetaData(ospec.relationId)/><#t>
  <#assign el_name = ospec.rowElementName><#t>
  <#assign list_el_name = ospec.rowCollectionElementName/><#t>
  <#assign el_type_name = el_type(ospec.relationId)/><#t>
  <#assign list_el_type_name = list_el_type(ospec.relationId)/><#t>
  
  <#if !(toplevel_el_rels??) || toplevel_el_rels?seq_contains(ospec.relationId)>
  <element name="${el_name}" type="tns:${el_type_name}"/>
  </#if>

  <complexType name="${el_type_name}">
    <sequence>
      <#list relmd.fields as f>
      <#assign xmlschema_type = qgen.getXmlSchemaTypeForJdbcTypeCode(f.jdbcTypeCode)>
      <element name="${f.name?lower_case}" type="${xmlschema_type}" minOccurs="<#if f.nullable>0<#else>1</#if>"/>
      </#list>
      <!-- child list elements -->
      <#list ospec.childOutputSpecs as c_ospec>
      <element name="${c_ospec.rowCollectionElementName}" type="tns:${list_el_type(c_ospec.relationId)}" minOccurs="${child_els_opt?string('0','1')}"/>
      </#list>
      <!-- parent elements -->
      <#list ospec.parentOutputSpecs as p_ospec>
      <element name="${p_ospec.rowElementName}" type="tns:${el_type(p_ospec.relationId)}" minOccurs="${parent_els_opt?string('0','1')}"/>
      </#list>
    </sequence>
  </complexType>

  <#if !toplevel_list_el_rels?? || toplevel_list_el_rels?seq_contains(ospec.relationId)>
  <element name="${list_el_name}" type="tns:${list_el_type_name}"/>
  </#if>

  <complexType name="${list_el_type_name}">
    <sequence>
      <element name="${el_name}" type="tns:${el_type_name}"	minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>
  
</#list>
</schema>

<#function el_type rel_id> 
  <#return rel_id>
</#function>

<#function list_el_type rel_id> 
  <#return rel_id + "-list">
</#function>
